name: Workflow run Type
run-name:  Rodando type ${{github.event_name}}
on: 
  workflow_run:
    workflows: [Trigger 1]
    types: [requested]
    # types: [in_progress]
    # types: [completed]
    # types: [requested,in_progress,completed]
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Workflow que foi trigado"
