name: Config variavel
run-name: ${{ github.actor }} testando 🚀
on: [push, workflow_dispatch]
jobs:
  exibevar:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir variável
        run: echo "var= ${{ vars.var_test }}"