name: Config variavel e secret
run-name: ${{ github.actor }} testando 🚀
on: [push, workflow_dispatch]
jobs:
  exibevar:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: echo "usuario= ${{vars.var_test}} senha= ${{secrets.password}}"