name: Config variavel e secret
run-name: ${{ github.actor }} testando 🚀
on: [push, workflow_dispatch]
jobs:
  exibevar:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir variável
        run: echo "${{ vars.var_test }}"

      - name: Exibir secret
        run: echo "${{ secrets.password }}"