name: Config vsecret
run-name: ${{ github.actor }} testando  🚀
on: [push, workflow_dispatch]
jobs:
  exibevar:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir secret
        run: echo "secret: ${{ secrets.password }}"