name: Push template branch
run-name: Rodando ${{github.event_name}} branch
on:
  push:
    branches:
      - main
      - master
      - develop
jobs:
  aoenviar:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: echo "comentário básico de push do workflow"

