name: "Template PR branch main"
run-name: "Rodando no ${{github.event_name}}"
on: 
  pull_request:
    branches:
      - main
      # - develop
jobs:
  testepull:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo "Comentário PR TESTE"