name: "Template PR Type"
run-name: "Rodando no ${{github.event_name}}"
on: 
  pull_request:
    types:
      - opened
      - reopened
      - closed
jobs:
  testepull:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo "Comentário PR TESTE"